apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}-cosmos
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}-cosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.name}}-cosmos
  template:
    metadata:
      labels:
        aadpodidbinding: {{gitops.config.mi.name}}
        app: {{gitops.name}}-cosmos
        deploy: {{gitops.deploy}}
        version: beta-{{gitops.version}}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          args:
          - --prometheus
          - --url-prefix
          - /cosmos
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ngsa-secrets
      nodeSelector:
        agentpool: npuser01

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}-cosmos
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}-cosmos

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{gitops.name}}-cosmos-ingress
  namespace: {{gitops.namespace}}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: default
    traefik.ingress.kubernetes.io/router.middlewares: ngsa-stripprefix@file
spec:
  tls:
  - hosts:
      - {{gitops.config.domain}}
  rules:
  - host: {{gitops.config.domain}}
    http:
      paths:
      - path: /cosmos
        pathType: Prefix
        backend:
          service:
            name: {{gitops.name}}-cosmos
            port:
              number: 8080
