{
 "title": "k6 Load Testing Results (Prometheus)",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the Prometheus.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "scenario",
    "query": {
     "query": "label_values(k6_iterations_total, scenario)"
    }
   },
   {
    "name": "domain",
    "label": "domain",
    "query": {
     "query": "label_values(k6_http_reqs, url)"
    }
   },
   {
    "name": "HttpMetricName",
    "label": "HttpMetricName",
    "query": "blocked,connecting,duration,receiving,sending,tls_handshaking,waiting"
   }
  ]
 },
 "panels": [
  { "title": "Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(k6_vus)", "legendFormat": "Virtual Users" },
    { "expr": "sum(k6_vus_max)", "legendFormat": "Max Users" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{scenario=\"$scenario\"}[1m]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Iterations per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations_total[1m]))"
    }
   ]
  },
  {
   "title": "Requests Failed Rate (avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_failed_rate{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "% Failed Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_check{outcome=\"fail\"}[$__rate_interval])) / sum(rate(k6_check[$__rate_interval]))",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(k6_http_reqs_total{scenario=\"${scenario}\", url=~\".*${domain}.*\"}[2m]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Data",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received_total[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(k6_data_sent_total[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "K6 Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"k6\",phase=\"Running\",pod=~\"k6.*\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"k6\", phase=\"Pending\",pod=~\"k6.*\"}) ",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"k6\",pod=~\"k6.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Http Metrics for (${HttpMetricName})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Response time (${HttpMetricName})_p99(avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_p99{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "Max (${HttpMetricName})_p99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(k6_http_req_${HttpMetricName}_p99{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "Min (${HttpMetricName})_p99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(k6_http_req_${HttpMetricName}_p99{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "K6 latency (${HttpMetricName})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_p99{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) ",
     "legendFormat": "${HttpMetricName}_P99"
    }
   ]
  },
  { "title": "Request Details (${domain})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Query (${domain}) ",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) by (url, status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Status code (${domain})",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 31 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) by (status, method)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}