name: Build NGSA-App-PR

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

    paths:
      - 'Dockerfile'
      - '*.csproj'
      - '**.cs'
      - '.github/workflows/ngsa_pr.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: ghcr.io/retaildevcrews/ngsa-app

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_ID }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker Build
      run: |
        docker build . -t image
        
    - name: Docker Tag and Push
      run: |

        # run image with --version flag
        docker run --rm image --version

        # tag the repo with :dev
        docker tag image $DOCKER_REPO:dev

        # Push to the repo
        docker push -a $DOCKER_REPO
